extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
root: true
globals:
  insights: readable
rules:
  rulesdir/forbid-pf-relative-imports: 'off'
