extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:cypress/recommended'
  - "plugin:testing-library/react"
  - "plugin:jest-dom/recommended"
root: true
globals:
  insights: readable
rules:
  rulesdir/forbid-pf-relative-imports: 'off'
