# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: insights-remediations-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: remediations
    spec:
      envName: ${ENV_NAME}
      title: Remediations
      deploymentRepo: https://github.com/RedHatInsights/insights-remediations-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/remediations
      image: ${IMAGE}:${IMAGE_TAG}
      feoConfigEnabled: true
      serviceTiles:
        - id: remediations
          section: automation
          group: rhel
          title: Remediation Plans 
          href: /insights/remediations
          description: Use Ansible Playbooks to resolve configuration, security, and compliance issues identified on your RHEL systems.
          icon: InsightsIcon
        - id: remediations-ansible
          section: automation
          group: ansible
          title: Remediation Plans 
          href: /ansible/remediations
          description: Use Ansible Playbooks to resolve issues identified across your Ansible-managed hosts.
          icon: AnsibleIcon
      searchEntries:
        - id: RHEL.remediations
          title: Remediation Plans
          href: /insights/remediations
          description: Use Ansible Playbooks to resolve configuration, security, and compliance issues identified on your RHEL systems.
          alt_title:
            - Remediate
            - playbook
            - fix
            - solve
            - find it fix it
            - fifi
            - cloud connector
            - insights
            - automation
            - Ansible
            - patch
            - Remediation plans
        - id: Ansible.remediations
          title: Remediation Plans
          href: /ansible/remediations
          description: Use Ansible Playbooks to resolve issues identified across your Ansible-managed hosts.
          alt_title:
            - Remediate
            - playbook
            - fix
            - automation
            - tasks
            - ansible remediations
      bundleSegments:
        - segmentId: automation
          bundleId: insights
          position: 2200
          navItems:
            - id: remediations
              title: Automation Toolkit
              expandable: true
              routes:
                - id: remediations
                  title: Remediation Plans
                  href: /insights/remediations
                  icon: InsightsIcon
                  product: Red Hat Insights
        - segmentId: remediations
          bundleId: ansible
          position: 2300
          navItems:
            - id: ansible-remediations
              title: Remediation Plans
              href: /ansible/remediations
              icon: AnsibleIcon
              product: Ansible
      module:
        manifestLocation: /apps/remediations/fed-mods.json
        analytics:
          APIKey: "apRCg9V6oMXCcnTingqRYW6m1er4hkCW"
        config:
          supportCaseData:
            product: Red Hat Insights
            version: Remediations
        modules:
          - id: remediations
            module: ./RootApp
            routes:
              - pathname: /insights/remediations
              - pathname: /ansible/remediations
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-remediations/remediations-frontend
